name: Deploy with CF CLI
description: Uses the cf CLI to push app
inputs:
  cf-username:
    description: cf username
    required: true
  cf-password:
    description: cf password
    required: true
  cf-space:
    description: cf space
    required: true
  manifest:
    description: cf manifest file
    default: manifest.yml
runs:
  using: "composite"
  steps:
    - name: Log in to Cloud Foundry
      shell: bash
      run: |
        cf login -u ${{ inputs.cf-username }} -p ${{ inputs.cf-password }} -a api.fr.cloud.gov -o doi-onrr -s ${{ inputs.cf-space }}

    - name: Push to Cloud Foundry
      shell: bash
      run: |
        cf push -f ${{ inputs.manifest }}