version: 2.1

orbs:
  node: circleci/node@6.3.0

executors:
  blog-executor:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge

workflows:
  deploy-prod-workflow:
    jobs:
      - build:
          filters:
            branches:
              only: master
      - deploy:
          requires: 
            - build
          context:
            - org-global
            - PROD
          filters:
            branches:
              only: master

  deploy-dev-workflow:
    jobs:
      - build:
          filters:
            branches:
              ignore: master
      - deploy:
          requires: 
            - build
          context:
            - org-global
            - DEV
          filters:
            branches:
              ignore: master

jobs:
  build:
    executor: blog-executor
    steps:
      - checkout
      - node/install:
          node-version: '18.20.4'
      - node/install-packages
      - run:
          name: Build gatsby
          command: npm run build
      - persist_to_workspace:
          root: ~/project
          paths: 
            - .
  deploy:
    executor: blog-executor
    steps:
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy to cloud.gov
          command: |
            chmod +x ~/project/.circleci/scripts/deploy.sh
            ~/project/.circleci/scripts/deploy.sh --branch "$CIRCLE_BRANCH"