version: 2.1

orbs:
  node: circleci/node@5.2.0

jobs:
  preview:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge
    environment:
      TEST_REPORTS: /tmp/test-reports
    steps:
      - checkout
      - node/install:
          node-version: '12.13.0'
      - node/install-packages
      - run:
          name: Build gatsby
          command: npm run build
      - run:
          name: deploy preview to cloud.gov
          command: |
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf8-cli
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o doi-onrr -s dev -v
            cf push dev-blog-nrrd -f ./manifest.yml


  dev:
    docker:
      - image: cimg/base:stable
    resource_class: xlarge
    steps:
      - checkout
      - node/install:
          node-version: '12.13.0'
      - node/install-packages
      - run:
          name: Build gatsby
          command: npm run build
      - run:
          name: deploy to cloud.gov
          command: |
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf8-cli
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o doi-onrr -s dev -v
            cf push dev-blog-nrrd -f ./manifest.yml
      - run:
          name: clean up
          command: |
            which cf
            bash ./.circleci/cleanup.sh

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          node-version: '12.13.0'
      - node/install-packages
      - run:
          name: Build gatsby
          command: npm run build
      - run:
          name: deploy preview to cloud.gov
          command: |
            wget -q -O - https://packages.cloudfoundry.org/debian/cli.cloudfoundry.org.key | sudo apt-key add -
            echo "deb https://packages.cloudfoundry.org/debian stable main" | sudo tee /etc/apt/sources.list.d/cloudfoundry-cli.list
            sudo apt-get update
            sudo apt-get install cf8-cli
            cf api https://api.fr.cloud.gov
            cf auth "$CF_USERNAME" "$CF_PASSWORD"
            cf target -o doi-onrr -s prod
            cf push blog-nrrd -f ./manifest.yml


workflows:
  preview:
    jobs:
      - preview:
          context:
            - org-global
            - DEV
          filters:
            branches:
              ignore:
                - master
                - dev

  deploy:
    jobs:
      - deploy:
          context:
            - org-global
            - PROD
          filters:
            branches:
              only: master

  dev:
    jobs:
      - dev:
          context:
            - org-global
            - DEV
          filters:
            branches:
              only: dev
