name: Build and deploy

on:
  push:
    branches-ignore:
      - master
  
  pull_request:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-dir: ${{ steps.set-output.outputs.build-dir }}

    steps:
    
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup node
      uses: actions/setup-node@v4
      with:
        node-version: 18
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build application
      run: npm run build --if-present

    - name: Rename _partytown directory
      run: |
        if [ -d public/_partytown ]; then
          mv public/_partytown public/~partytown
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        path: |
          public/

  deploy:

    needs: build
    
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./public

      - name: Install CF CLI
        uses: ./.github/actions/cf-install

      - name: Deploy to cf
        uses: ./.github/actions/cf-deploy
        with: 
          cf-username: ${{ secrets.CF_USERNAME }}
          cf-password: ${{ secrets.CF_PASSWORD }}
          cf-space: dev
          manifest: manifest.dev.yml